# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  # secret_key_base: 187d04af078e5a13e0904ac130b560a2271222ea020514152bbbc00cf517f1d529c95d76793ab85e57e4046dc21ca9e6d0679905fb92caeeb736384d4cdb7734
  secret_key_base: <%= CONFIG[:secret_key_base] %>

test:
  # secret_key_base: 052bb2ff3d442679e99e41fea8f36c1bc33bb1764934a669b1de0f4391d36325999570c5b5ab933eebe97afd41732c91f1c3ec780626991c5810820f615e5bf7
  secret_key_base: <%= CONFIG[:secret_key_base] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # secret_key_base: e613a26529f9c26746c5c586e047713aff3a2a6fd7fefe0e57d81ccbc1b80c326f949d472c1ed191fafbb0072a0dd14ce56bf15b160fb9b8a61a89cef1e56912
  secret_key_base: <%= CONFIG[:secret_key_base] %>